### ISSUE TITLE
Can not compile solution

### ISSUE THREAD

**Issue by Puresoft** [wyattoday/wyupdate#5]
I tried to compile the project but got an error in frmMain.cs line 149
selfUpdateFromRC1 does not exist.

selfUpdateFromRC1 is a boolean but never defined. 

regards
Robert

**Comment by wyattoday** [comment]
Hey Robert,

This was fixed in our local dev branch. I've pushed it to this public mirror (fixed in current master).

**Comment by Puresoft** [comment]
Thanks!
