### ISSUE TITLE
Why enforcing to launch app as non-elevated after update ?

### ISSUE THREAD

**Issue by xmenxwk** [wyattoday/wyupdate#8]
I have an app that runs elevated, but after update, its no longer elevated, causing all kinds of permissions issue. I looked at the source found it was in fact being forced to run as limited process. Why is that ? it should have some settings through arguments to do that or not to do that.

**Comment by wyattoday** [comment]
When clicking ["Execute file after update" you can choose "Same as wyUpdate", "Not elevated" or "Elevated".](https://wyday.com/wybuild/help/executing-files.php)

This isn't an issue. It's a question for our forum: https://wyday.com/forum/
